export const INDIA_LOCATIONS = {
  "Andaman and Nicobar Islands": ["Nicobar", "North and Middle Andaman", "South Andaman"],
  "Andhra Pradesh": ["Anantapur", "Chittoor", "East Godavari", "Guntur", "Krishna", "Kurnool", "Nellore", "Visakhapatnam"],
  "Arunachal Pradesh": ["Changlang", "East Siang", "Itanagar", "Papum Pare", "Tawang", "West Kameng"],
  Assam: ["Barpeta", "Cachar", "Dibrugarh", "Goalpara", "Jorhat", "Kamrup Metro", "Nagaon", "Silchar"],
  Bihar: ["Bhagalpur", "Darbhanga", "Gaya", "Muzaffarpur", "Patna", "Purnia", "Samastipur", "Vaishali"],
  Chandigarh: ["Chandigarh"],
  Chhattisgarh: ["Bilaspur", "Durg", "Jagdalpur", "Korba", "Raigarh", "Raipur", "Rajnandgaon", "Surguja"],
  "Dadra and Nagar Haveli and Daman and Diu": ["Daman", "Diu", "Silvassa"],
  Delhi: ["Central Delhi", "East Delhi", "New Delhi", "North Delhi", "North West Delhi", "South Delhi", "West Delhi"],
  Goa: ["North Goa", "Panaji", "Ponda", "South Goa", "Vasco da Gama"],
  Gujarat: ["Ahmedabad", "Anand", "Bhavnagar", "Gandhinagar", "Jamnagar", "Rajkot", "Surat", "Vadodara"],
  Haryana: ["Ambala", "Faridabad", "Gurugram", "Hisar", "Karnal", "Kurukshetra", "Panipat", "Rohtak"],
  "Himachal Pradesh": ["Chamba", "Hamirpur", "Kangra", "Kullu", "Mandi", "Shimla", "Sirmaur", "Solan"],
  "Jammu and Kashmir": ["Anantnag", "Baramulla", "Jammu", "Kathua", "Pulwama", "Srinagar", "Udhampur"],
  Jharkhand: ["Bokaro", "Deoghar", "Dhanbad", "East Singhbhum", "Hazaribagh", "Ramgarh", "Ranchi"],
  Karnataka: ["Ballari", "Belagavi", "Bengaluru Rural", "Bengaluru Urban", "Davanagere", "Kalaburagi", "Mangaluru", "Mysuru"],
  Kerala: ["Alappuzha", "Ernakulam", "Kannur", "Kollam", "Kottayam", "Kozhikode", "Palakkad", "Thiruvananthapuram"],
  Ladakh: ["Kargil", "Leh"],
  Lakshadweep: ["Kavaratti"],
  "Madhya Pradesh": ["Bhopal", "Gwalior", "Indore", "Jabalpur", "Rewa", "Sagar", "Satna", "Ujjain"],
  Maharashtra: ["Ahmednagar", "Amravati", "Aurangabad", "Kolhapur", "Mumbai City", "Nagpur", "Nashik", "Pune", "Thane"],
  Manipur: ["Bishnupur", "Churachandpur", "Imphal East", "Imphal West", "Senapati", "Thoubal", "Ukhrul"],
  Meghalaya: ["East Khasi Hills", "Jaintia Hills", "Ri Bhoi", "Shillong", "West Garo Hills"],
  Mizoram: ["Aizawl", "Champhai", "Kolasib", "Lunglei", "Mamit", "Saiha"],
  Nagaland: ["Dimapur", "Kiphire", "Kohima", "Mokokchung", "Mon", "Phek", "Tuensang"],
  Odisha: ["Balasore", "Berhampur", "Bhadrak", "Bhubaneswar", "Cuttack", "Ganjam", "Koraput", "Sambalpur"],
  Puducherry: ["Karaikal", "Mahe", "Puducherry", "Yanam"],
  Punjab: ["Amritsar", "Bathinda", "Jalandhar", "Ludhiana", "Mohali", "Patiala", "Pathankot", "Sangrur"],
  Rajasthan: ["Ajmer", "Alwar", "Bikaner", "Jaipur", "Jodhpur", "Kota", "Sikar", "Udaipur"],
  Sikkim: ["East Sikkim", "Gangtok", "Namchi", "North Sikkim", "South Sikkim", "West Sikkim"],
  "Tamil Nadu": ["Chennai", "Coimbatore", "Cuddalore", "Erode", "Madurai", "Salem", "Thanjavur", "Tiruchirappalli"],
  Telangana: ["Adilabad", "Hyderabad", "Karimnagar", "Khammam", "Nalgonda", "Nizamabad", "Warangal", "Rangareddy"],
  Tripura: ["Agartala", "Dhalai", "Gomati", "Khowai", "North Tripura", "Sepahijala", "South Tripura"],
  "Uttar Pradesh": ["Agra", "Aligarh", "Bareilly", "Ghaziabad", "Gorakhpur", "Kanpur Nagar", "Lucknow", "Meerut", "Prayagraj", "Varanasi"],
  Uttarakhand: ["Dehradun", "Haridwar", "Haldwani", "Nainital", "Pauri Garhwal", "Rishikesh", "Udham Singh Nagar"],
  "West Bengal": ["Asansol", "Bankura", "Darjeeling", "Durgapur", "Howrah", "Kolkata", "Malda", "Murshidabad", "Siliguri"]
};

export const INDIA_STATES = Object.keys(INDIA_LOCATIONS);
